spring.application.name=coop-servicios-backend

# Configuración del puerto del servidor
server.port=8080

# Configuración de PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/coop_servicios_db
spring.datasource.username=postgres
# Colocar contraseña personal
spring.datasource.password=159753
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate (ORM)
# "update" creará/actualizará las tablas automáticamente en base a las entidades (solo para desarrollo)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
